### ISSUE TITLE
Interface Calculadora possui método estático

### ISSUE THREAD

**Issue by panoramix360** [andersonfcz/com.engelox.calculadora#11]
Não fez muito sentido possuir uma interface Calculadora com um método estático, vocês poderiam ter utilizado uma classe mesmo nesse caso.

Uma interface é mais utilizada ao criar um contrato com outras classes.

Exemplo:
Uma operação poderia ser uma (interface Operacao) que possui o método "calcular", e ai todas as operações específicas poderiam implementar essa interface Operacao e implementar de fato o método calcular.

Toda vez que criamos uma interface é esperado que a mesma seja implementado por outras classes.

**Comment by andersonfcz** [comment]
Realmente não estava fazendo sentido ela ser uma interface.
Converti para uma classe

**Comment by panoramix360** [comment]
Beleza!

Quando você quer misturar uma interface com alguns métodos de interpretação, lembre-se que você pode utilizar uma classe Abstrata.
