### ISSUE TITLE
Lembrar de manter a linguagem do repositório

### ISSUE THREAD

**Issue by panoramix360** [andersonfcz/com.engelox.calculadora#2]
Lembrem-se sempre de manter a linguagem que está sendo utilizada no repositório que vocês estiverem trabalhando.

Ex.: Se o projeto estiver em PT-BR, tentem commitar sempre em PT-BR

**Comment by Wrubleski** [comment]
Cientes. A partir de agora, iremos usar inglês como língua padrão do repositório.
