### ISSUE TITLE
Try-catch na classe Main

### ISSUE THREAD

**Issue by panoramix360** [andersonfcz/com.engelox.calculadora#5]
Envolver todas as operações do método main() por um try-catch e colocar o app.close() e menu.close() no finally, pra sempre serem executados no fim da execução.

**Comment by Wrubleski** [comment]
Feito. Encontramos um bug ao resolver essa issue. Já abri otra issue (#12) com o bug para resolvermos.

**Comment by panoramix360** [comment]
Boa! Quando finalizar pode fechar essa issue.
