### ISSUE TITLE
Variável sendo criada desnecessariamente

### ISSUE THREAD

**Issue by panoramix360** [andersonfcz/com.engelox.calculadora#6]
Na Classe Menu, na linha 16, não é necessário criar uma variável para logo depois retorná-la, pode retornar direto o valor.

**Comment by andersonfcz** [comment]
Verdade, foi um descuido. Vou me atentar mais a esses detalhes. 
Obrigado!

**Comment by panoramix360** [comment]
Sem problemas! Nem tudo fica perfeito no primeiro código mesmo, fica tranquilo :)
