### ISSUE TITLE
Variáveis em caixa alta

### ISSUE THREAD

**Issue by panoramix360** [andersonfcz/com.engelox.calculadora#7]
Na Classe App na linha 19, não é boa prática dar o nome de variáveis com caracteres em caixa alta.

Apenas quando forem estáticos ou constantes.

**Comment by andersonfcz** [comment]
Ela era mesmo uma constante e não havia sido adicionado o atributo final. 
Obrigado.

**Comment by panoramix360** [comment]
Vi aqui o seu commit, tem certeza que isso ai compilou?

O final quer dizer que a variável não pode ser mais atribuída nenhum valor, apenas na inicialização, dá uma testada

**Comment by andersonfcz** [comment]
Testei aqui e esta funcionando corretamente.
Minha ideia aqui foi tentar usar um conceito que eu li sobre imutabilidade. Depois que o resultado é atribuído e impresso a chamada do método é encerrado e todas as variáveis são limpas da heap. Novas operações são feitas com novas chamadas, que gerariam outro escopo.

**Comment by panoramix360** [comment]
Entendi o conceito sim!

Esqueci que o `final` quer dizer apenas que você só vai poder atribuir um valor apenas 1x.
